<Project><PropertyGroup><Version>0.3.0</Version><Product>WT - Blog Generator</Product><Company>Wheeltrade</Company><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableWindowsTargeting>true</EnableWindowsTargeting><LangVersion>latest</LangVersion><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><Deterministic>true</Deterministic><RuntimeIdentifiers>win-x64</RuntimeIdentifiers></PropertyGroup></Project>