// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WheelContentManager.Infrastructure;

#nullable disable

namespace WheelContentManager.Infrastructure.Migrations
{
    [DbContext(typeof(ContentDb))]
    partial class ContentDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WheelContentManager.Core.ApplicationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("WheelContentManager.Core.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ApprovedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutomationRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportFolder")
                        .HasColumnType("TEXT");

                    b.Property<long>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PromptVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId")
                        .IsUnique();

                    b.HasIndex("AutomationRunId", "GalleryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WheelContentManager.Core.ArticleVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PromptVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "Language", "Revision")
                        .IsUnique();

                    b.ToTable("ArticleVersions");
                });

            modelBuilder.Entity("WheelContentManager.Core.AutomationRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Report")
                        .HasColumnType("TEXT");

                    b.Property<long>("Started")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodKey")
                        .IsUnique();

                    b.ToTable("AutomationRuns");
                });

            modelBuilder.Entity("WheelContentManager.Core.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WheelContentManager.Core.ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("WheelContentManager.Core.Gallery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlogBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BlogCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlogStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Brand")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DetailsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExistingBlogUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstDetected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastChecked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissingData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourcePublished")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpecificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VisualAnalysis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.HasIndex("Brand", "ExternalId")
                        .IsUnique();

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("WheelContentManager.Core.GalleryImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsageAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId", "Url")
                        .IsUnique();

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("WheelContentManager.Core.GenerationJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<long>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GenerationJobs");
                });

            modelBuilder.Entity("WheelContentManager.Core.NotificationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("NotificationHistory");
                });

            modelBuilder.Entity("WheelContentManager.Core.PromptTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Brand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Brand")
                        .IsUnique();

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("WheelContentManager.Core.PromptVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EditorialDocumentVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PromptTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId", "Revision")
                        .IsUnique();

                    b.ToTable("PromptVersions");
                });

            modelBuilder.Entity("WheelContentManager.Core.SourceReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.ToTable("SourceReferences");
                });

            modelBuilder.Entity("WheelContentManager.Core.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("WheelContentManager.Core.WheelSpecification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableSizes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Certifications")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Et")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Finish")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontWidth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pcd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RearSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("RearWidth")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WheelSpecifications");
                });

            modelBuilder.Entity("WheelContentManager.Core.Article", b =>
                {
                    b.HasOne("WheelContentManager.Core.Gallery", "Gallery")
                        .WithMany()
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("WheelContentManager.Core.ArticleVersion", b =>
                {
                    b.HasOne("WheelContentManager.Core.Article", null)
                        .WithMany("Versions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WheelContentManager.Core.Gallery", b =>
                {
                    b.HasOne("WheelContentManager.Core.Brand", null)
                        .WithMany()
                        .HasForeignKey("Brand")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WheelContentManager.Core.WheelSpecification", "Specification")
                        .WithMany()
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WheelContentManager.Core.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specification");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("WheelContentManager.Core.GalleryImage", b =>
                {
                    b.HasOne("WheelContentManager.Core.Gallery", null)
                        .WithMany("Images")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WheelContentManager.Core.PromptVersion", b =>
                {
                    b.HasOne("WheelContentManager.Core.PromptTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WheelContentManager.Core.SourceReference", b =>
                {
                    b.HasOne("WheelContentManager.Core.Gallery", null)
                        .WithMany("Sources")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WheelContentManager.Core.Article", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("WheelContentManager.Core.Gallery", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("WheelContentManager.Core.PromptTemplate", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
